image:
  file: Dockerfile

tasks:
  - before: |
      export PATH=/usr/lib/dart/bin:$FLUTTER_HOME/bin:$ANDROID_HOME/bin:$ANDROID_HOME/platform-tools$ANDROID_HOME/tools:$PATH
      mkdir -p /home/gitpod/.android
      touch /home/gitpod/.android/repositories.cfg
    init: |
      echo "Installing Flutter SDK..."
      yes | flutter doctor --android-licenses
      flutter create example
      cd ./example
      flutter pub get
      flutter config --enable-web
      flutter doctor      
      echo y | /home/gitpod/tools/bin/sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3";
    command: |
      echo "OK!"
vscode:
  extensions:
    - Dart-Code.dart-code@3.5.1:W6zqgIED1gxtkBH/pbfGXA==
    - Dart-Code.flutter@3.5.1:0FyuzXye7dV19PNst3+Llg==
